services:
  app:
    container_name: mahayoga-cards-microservice
    build: .
    image: mahayoga-cards-microservice-image
    restart: unless-stopped
    networks:
      - gateway

networks:
  gateway:
    name: mahayoga-gateway-network
    external: true